##Class: jiocloud::openstack::keystone
class jiocloud::openstack::keystone (
  $admin_email = $jiocloud::params::admin_email,
  $admin_password = $jiocloud::params::admin_password,
  $admin_token = $jiocloud::params::admin_token,
  $cinder_admin_address = $jiocloud::params::cinder_admin_address,
  $cinder_internal_address = $jiocloud::params::cinder_internal_address,
  $cinder_protocol = $jiocloud::params::cinder_protocol,
  $cinder_public_address = $jiocloud::params::cinder_public_address,
  $cinder_public_port = $jiocloud::params::cinder_public_port,
  $db_host_ip = $jiocloud::params::db_host_ip,
  $debug = $jiocloud::params::debug,
  $glance_admin_address = $jiocloud::params::glance_admin_address,
  $glance_internal_address = $jiocloud::params::glance_internal_address,
  $glance_public_address = $jiocloud::params::glance_public_address,
  $glance_public_port = $jiocloud::params::glance_public_port,
  $glance_public_protocol = $jiocloud::params::glance_protocol,
  $keystone_admin_address = $jiocloud::params::keystone_admin_address,
  $keystone_admin_listen_port = $jiocloud::params::keystone_admin_listen_port,
  $keystone_admin_url = $jiocloud::params::keystone_admin_url,
  $keystone_cache_backend = $jiocloud::params::keystone_cache_backend,
  $keystone_cache_backend_argument = $jiocloud::params::keystone_cache_backend_argument,
  $keystone_cache_config_prefix = $jiocloud::params::keystone_cache_config_prefix,
  $keystone_cache_enabled = $jiocloud::params::keystone_cache_enabled,
  $keystone_cache_expiration_time = $jiocloud::params::keystone_cache_expiration_time,
  $keystone_db_password = $jiocloud::params::keystone_db_password,
  $keystone_internal_address = $jiocloud::params::keystone_internal_address,
  $keystone_internal_url = $jiocloud::params::keystone_internal_url,
  $keystone_public_address = $jiocloud::params::keystone_public_address,
  $keystone_public_listen_port = $jiocloud::params::keystone_public_listen_port,
  $keystone_public_url = $jiocloud::params::keystone_public_url,
  $keystone_token_format = $jiocloud::params::keystone_token_format,
  $neutron_admin_address = $jiocloud::params::neutron_admin_address,
  $neutron_enabled = $jiocloud::params::neutron_enabled,
  $neutron_internal_address = $jiocloud::params::neutron_internal_address,
  $neutron_protocol = $jiocloud::params::neutron_protocol,
  $neutron_public_address = $jiocloud::params::neutron_public_address,
  $neutron_public_port = $jiocloud::params::neutron_port,
  $nova_admin_address = $jiocloud::params::nova_admin_address,
  $nova_internal_address = $jiocloud::params::nova_internal_address,
  $nova_protocol = $jiocloud::params::nova_protocol,
  $nova_public_address = $jiocloud::params::nova_public_address,
  $nova_public_port = $jiocloud::params::nova_public_port,
  $region = $jiocloud::params::region,
  $service_user_password = $jiocloud::params::service_user_password,
  $verbose = $jiocloud::params::verbose,
  $admin_password = $jiocloud::params::admin_password,
  $ceph_radosgw_admin_address = $jiocloud::params::ceph_radosgw_admin_address,
  $ceph_radosgw_internal_address = $jiocloud::params::ceph_radosgw_internal_address,
  $ceph_radosgw_protocol = $jiocloud::params::ceph_radosgw_protocol,
  $ceph_radosgw_public_address = $jiocloud::params::object_storage_public_address,
  $ceph_radosgw_public_port = $jiocloud::params::ceph_radosgw_public_port,
  $keystone_accepted_roles = $jiocloud::params::keystone_accepted_roles,
  $keystone_admin_port = $jiocloud::params::keystone_admin_port,
  $keystone_protocol = $jiocloud::params::keystone_protocol,
  $keystone_public_address = $jiocloud::params::keystone_public_address,
  $keystone_public_port = $jiocloud::params::keystone_public_port,
  $keystone_version = $jiocloud::params::keystone_version,
  $region = $jiocloud::params::region,
) {
  class { 'openstack::keystone':
    db_host => $db_host_ip,
    db_password => $keystone_db_password,
    admin_token => $admin_token,
    admin_email           	=> $admin_email,
    admin_password        	=> $admin_password,
    ## cache configuration
    keystone_cache_enabled	=> $keystone_cache_enabled,
    keystone_cache_config_prefix	=> $keystone_cache_config_prefix,
    keystone_cache_expiration_time	=> $keystone_cache_expiration_time,
    keystone_cache_backend	=> $keystone_cache_backend,
    keystone_cache_backend_argument	=> $keystone_cache_backend_argument,
    ###End: Cache configuration
    keystone_public_port		=> $keystone_public_listen_port,
    keystone_admin_port		=> $keystone_admin_listen_port,
    token_format		=> $keystone_token_format,
    region		 	=> $region,
    glance_user_password  	=> $service_user_password,
    nova_user_password    	=> $service_user_password,
    cinder_user_password  	=> $service_user_password,
    neutron_user_password 	=> $service_user_password,
    neutron			=> $neutron_enabled,
    public_address        	=> $keystone_public_address,
    internal_address	=> $keystone_internal_address,
    admin_address		=> $keystone_admin_address,
    keystone_public_url	=> $keystone_public_url,
    keystone_admin_url	=> $keystone_admin_url,
    keystone_internal_url => $keystone_internal_url,

    neutron_public_address => $neutron_public_address,
    neutron_internal_address => $neutron_internal_address,
    neutron_admin_address => $neutron_admin_address,
    neutron_public_port => $neutron_public_port,
    neutron_public_protocol => $os_env::neutron_protocol,
    neutron_internal_protocol => $os_env::neutron_protocol,

    cinder_public_address  => $cinder_public_address,
    cinder_internal_address        => $cinder_internal_address,
    cinder_admin_address           => $cinder_admin_address,
    cinder_public_port	=> $cinder_public_port,
    cinder_public_protocol	=> $cinder_protocol,

    nova_public_address  => $nova_public_address,
    nova_internal_address        => $nova_internal_address,
    nova_admin_address           => $nova_admin_address,
    nova_public_port	 => $nova_public_port,
    nova_public_protocol	=> $nova_protocol,

    glance_public_address  => $glance_public_address,
    glance_internal_address => $glance_internal_address,
    glance_admin_address    => $glance_admin_address,
    glance_public_port	=> $glance_public_port,
    glance_public_protocol	=> $glance_public_protocol,
    glance_internal_protocol => $glance_public_protocol,
    verbose => $verbose,
    debug => $debug,
  }

  if $ceph_radosgw_enabled { 
    class { 'keystone::radosgw':
      keystone_accepted_roles => $keystone_accepted_roles,
      region                  => $region,
      public_address          => $ceph_radosgw_public_address,
      public_port             => $ceph_radosgw_public_port,
      admin_address           => $ceph_radosgw_admin_address,
      internal_address        => $ceph_radosgw_internal_address,
#      port           		=> $ceph_radosgw_internal_port,
      public_protocol		=> $ceph_radosgw_protocol,
    }
  }
 
  class { 'openstack::auth_file':
    admin_password  => $admin_password,
    controller_node => $keystone_public_address,
    region_name     => $region,
    keystone_protocol => $keystone_protocol,
    keystone_port   => $keystone_public_port,
    keystone_admin_port     => $keystone_admin_port,
    keystone_version        => $keystone_version,
    admin_tenant    => 'admin',
  }
}